times = int(input())
for i in range(times):
    n = input()
    n = n.replace("-", "")
    n = n[0:10]
    n = n.lower()
    n = n.replace("a", "2")
    n = n.replace("b", "2")
    n = n.replace("c", "2")
    n = n.replace("d", "3")
    n = n.replace("e", "3")
    n = n.replace("f", "3")
    n = n.replace("g", "4")
    n = n.replace("h", "4")
    n = n.replace("i", "4")
    n = n.replace("j", "5")
    n = n.replace("k", "5")
    n = n.replace("l", "5")
    n = n.replace("m", "6")
    n = n.replace("n", "6")
    n = n.replace("o", "6")
    n = n.replace("p", "7")
    n = n.replace("q", "7")
    n = n.replace("r", "7")
    n = n.replace("s", "7")
    n = n.replace("t", "8")
    n = n.replace("u", "8")
    n = n.replace("v", "8")
    n = n.replace("w", "9")
    n = n.replace("x", "9")
    n = n.replace("y", "9")
    n = n.replace("z", "9")
    n_list = list(n)
    n_list.insert(3, "-")
    n_list.insert(8, "-")
    m2 = "".join(n_list)
    print(m2)
        

    
        